[package]
name = "image-encrypter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23"
rexiv2 = "0.10.0"

num_cpus = "1.13.0"
rayon = "1.5.1"
